import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo,useState } from "react";
import { CalendarEntry, formatHmSec, makeId, removeCalendar, upsertCalendar } from "@/lib/kompsaldo";
import { deductionSeconds, getShift, isWorkday, shiftEndForDate, SUNDAY_NIGHT_UNPAID_BREAK } from "@/lib/shifts";
import { useKompSaldo } from "@/lib/useKompSaldo";
export const Route=createFileRoute("/ga-hem")({component:SchemaKomp});
const pad=(n:number)=>String(n).padStart(2,"0");
const formatSwedishTimeInput=(raw:string)=>{
 const digits=raw.replace(/\D/g,"").slice(0,4);
 if(digits.length<=2)return digits;
 return `${digits.slice(0,2)}:${digits.slice(2)}`;
};
const isValidSwedishTime=(value:string)=>{
 const m=/^(\d{2}):(\d{2})$/.exec(value);
 if(!m)return false;
 const h=Number(m[1]),min=Number(m[2]);
 return h>=0&&h<=23&&min>=0&&min<=59;
};
const dateKey=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;
function SchemaKomp(){const{state,ready,update}=useKompSaldo();const now=new Date();const[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const[selected,setSelected]=useState<string|null>(null);const[mode,setMode]=useState<"menu"|"early"|"multi">("menu");const[leave,setLeave]=useState("");const[multi,setMulti]=useState<string[]>([]);const[showOff,setShowOff]=useState(false);
 const days=useMemo(()=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),offset=(first+6)%7,count=new Date(y,m+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>dateKey(y,m,i+1))]},[month]);
 const entry=selected?state.calendar.find(e=>e.date===selected):undefined;const shift=selected?shiftEndForDate(getShift(state.shift),selected):null;const fullSec=selected&&shift?deductionSeconds(selected,state.shift,shift.start,shift.end):null;const earlySec=selected&&isValidSwedishTime(leave)?deductionSeconds(selected,state.shift,leave):null;const sundayBlocked=selected&&state.shift==="natt"&&new Date(`${selected}T12:00:00`).getDay()===0&&!SUNDAY_NIGHT_UNPAID_BREAK;
 const save=(type:"SCHEDULED_OFF"|"FULL_COMP_DAY"|"LEAVE_EARLY")=>{if(!selected||!shift)return;const deductionSec=type==="SCHEDULED_OFF"?0:type==="FULL_COMP_DAY"?fullSec:earlySec;if(deductionSec==null)return;const nowIso=new Date().toISOString();const e:CalendarEntry={id:entry?.id??makeId(),date:selected,type,shift:state.shift,shiftStart:shift.start,shiftEnd:shift.end,leaveTime:type==="LEAVE_EARLY"?leave:undefined,deductionSec,createdAt:entry?.createdAt??nowIso,updatedAt:nowIso};update(s=>upsertCalendar(s,e));setSelected(null);setLeave("");setMode("menu")};
 const saveMulti=()=>{update(s=>multi.reduce((acc,date)=>{const sh=shiftEndForDate(getShift(acc.shift),date),t=new Date().toISOString();return upsertCalendar(acc,{id:makeId(),date,type:"SCHEDULED_OFF",shift:acc.shift,shiftStart:sh.start,shiftEnd:sh.end,deductionSec:0,createdAt:t,updatedAt:t})},s));setMulti([]);setMode("menu")};
 if(!ready)return null;return <main className="min-h-screen bg-background pb-16"><div className="mx-auto max-w-md px-5 pt-8"><header className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Schema &amp; komp</h1><p className="text-sm text-muted-foreground">{getShift(state.shift).name}skift</p></div><Link to="/" className="rounded-full bg-card px-4 py-2 text-sm shadow-card">Tillbaka</Link></header>
 <section className="rounded-3xl bg-card p-5 shadow-card"><div className="flex items-center justify-between"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} className="h-10 w-10 rounded-xl border">‹</button><p className="font-bold">{month.toLocaleDateString("sv-SE",{month:"long",year:"numeric"})}</p><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} className="h-10 w-10 rounded-xl border">›</button></div><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs text-muted-foreground">{"M T O T F L S".split(" ").map((x,i)=><span key={i}>{x}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{days.map((date,i)=>{if(!date)return <span key={`x${i}`}/>;const e=state.calendar.find(x=>x.date===date),picked=multi.includes(date);const cls=e?.type==="SCHEDULED_OFF"?"bg-success-soft border-success":e?.type==="FULL_COMP_DAY"?"bg-danger/15 border-danger":e?.type==="LEAVE_EARLY"?"bg-orange-100 border-orange-400":"bg-background border-border";return <button key={date} onClick={()=>{if(mode==="multi"){setMulti(v=>v.includes(date)?v.filter(x=>x!==date):[...v,date]);return}setSelected(date);setMode("menu");setLeave("")}} className={`relative h-11 rounded-xl border text-sm ${cls} ${picked?"ring-2 ring-brand":""} ${showOff&&e?.type==="SCHEDULED_OFF"?"ring-2 ring-success":""}`}>{Number(date.slice(-2))}{e&&<span className="absolute bottom-0.5 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full bg-foreground"/>}</button>})}</div><div className="mt-4 flex flex-wrap gap-3 text-xs"><span>🟢 Schemalagd ledig</span><span>🔴 Hel kompdag</span><span>🟠 Gå hem tidigare</span></div></section>
 <div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{setMode(mode==="multi"?"menu":"multi");setSelected(null)}} className="h-12 rounded-2xl bg-card font-semibold shadow-card">{mode==="multi"?"Avbryt val":"Lägg in lediga dagar"}</button><button onClick={()=>setShowOff(v=>!v)} className="h-12 rounded-2xl bg-card font-semibold shadow-card">{showOff?"Dölj lediga":"Visa lediga dagar"}</button></div>{mode==="multi"&&<button disabled={!multi.length} onClick={saveMulti} className="mt-3 h-14 w-full rounded-2xl bg-success font-bold text-success-foreground disabled:opacity-40">Spara {multi.length} lediga dagar</button>}
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/40 p-5"><div className="w-full max-w-md rounded-3xl bg-card p-6"><div className="flex justify-between"><div><h2 className="text-lg font-bold">{new Date(`${selected}T12:00:00`).toLocaleDateString("sv-SE",{weekday:"long",day:"numeric",month:"long"})}</h2><p className="text-sm text-muted-foreground">{shift?.start}–{shift?.end} · {getShift(state.shift).name}</p></div><button onClick={()=>setSelected(null)}>✕</button></div>{entry&&<div className="mt-4 rounded-2xl bg-background p-3 text-sm"><b>Befintligt:</b> {entry.type==="SCHEDULED_OFF"?"Schemalagd ledig":entry.type==="FULL_COMP_DAY"?"Hel kompdag":`Gå hem ${entry.leaveTime}`} {entry.deductionSec>0&&`· −${formatHmSec(entry.deductionSec)}`}</div>}
 {sundayBlocked&&<p className="mt-4 rounded-2xl bg-danger/10 p-3 text-sm text-danger">Söndagsnattens exakta obetalda lunchrast saknas i underlaget. Appen gissar inte tiden, så kompavdrag är spärrat för denna natt.</p>}
 {mode==="menu"&&<div className="mt-5 space-y-2"><button onClick={()=>save("SCHEDULED_OFF")} className="h-14 w-full rounded-2xl bg-success-soft font-semibold">Schemalagd ledig · 0 komp · 0 intjäning</button><button disabled={!isWorkday(selected,state.shift)||fullSec==null} onClick={()=>save("FULL_COMP_DAY")} className="h-14 w-full rounded-2xl bg-danger font-semibold text-danger-foreground disabled:opacity-40">Hel kompdag {fullSec!=null&&`· −${formatHmSec(fullSec)}`}</button><button disabled={!isWorkday(selected,state.shift)||sundayBlocked} onClick={()=>setMode("early")} className="h-14 w-full rounded-2xl border font-semibold disabled:opacity-40">Gå hem tidigare</button>{entry&&<button onClick={()=>{update(s=>removeCalendar(s,entry.id));setSelected(null)}} className="h-12 w-full rounded-2xl border border-danger text-danger">Ta bort registrering</button>}</div>}
 {mode==="early"&&<div className="mt-5"><label className="text-sm font-semibold">Tid du går hem</label><input type="text" inputMode="numeric" autoComplete="off" placeholder="14:30" maxLength={5} aria-label="Tid du går hem i 24-timmarsformat" value={leave} onChange={e=>setLeave(formatSwedishTimeInput(e.target.value))} className="mt-2 h-16 w-full rounded-2xl border bg-background px-4 text-2xl font-semibold tracking-wider"/><p className="mt-2 text-xs text-muted-foreground">Svensk tid · 24-timmarsformat (HH:MM), t.ex. 14:30</p>{leave&&earlySec!=null&&<div className="mt-4 rounded-2xl bg-background p-4"><p className="text-sm text-muted-foreground">Förhandsvisning av kompavdrag</p><p className="text-3xl font-bold text-danger">−{formatHmSec(earlySec)}</p><p className="mt-2 text-xs text-muted-foreground">Endast överlappande obetald rast dras bort. Betalda pauser räknas som arbetstid och kostar komp.</p></div>}<button disabled={earlySec==null} onClick={()=>save("LEAVE_EARLY")} className="mt-4 h-14 w-full rounded-2xl bg-danger font-bold text-danger-foreground disabled:opacity-40">Bekräfta</button><button onClick={()=>setMode("menu")} className="mt-2 h-12 w-full rounded-2xl border">Avbryt</button></div>}</div></div>}</div></main>}
