import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo,useRef,useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock3, History, Settings, Trash2, X } from "lucide-react";
import { ACCRUAL_MIN, CalendarEntry, SHIFT_NAME, formatExactMin, formatHmSec, fullDayDeduction, isCompanyVacation, isoWeek, makeId, parseHours, removeCalendar, todayKey, upsertCalendar } from "@/lib/kompsaldo";
import { SHIFTS, deductionSeconds, getShift, isWorkday, shiftEndForDate, SUNDAY_NIGHT_UNPAID_BREAK, type ShiftId } from "@/lib/shifts";
import { useKompSaldo } from "@/lib/useKompSaldo";
export const Route=createFileRoute("/")({component:Home});
const pad=(n:number)=>String(n).padStart(2,"0");
const formatSwedishTimeInput=(raw:string)=>{
 const digits=raw.replace(/\D/g,"").slice(0,4);
 if(digits.length<=2)return digits;
 return `${digits.slice(0,2)}:${digits.slice(2)}`;
};
const isValidSwedishTime=(value:string)=>{
 const m=/^(\d{2}):(\d{2})$/.exec(value);
 if(!m)return false;
 const h=Number(m[1]),min=Number(m[2]);
 return h>=0&&h<=23&&min>=0&&min<=59;
};const dateKey=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;
const monthDays=(month:Date)=>{const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),offset=(first+6)%7,count=new Date(y,m+1,0).getDate();return [...Array(offset).fill(null),...Array.from({length:count},(_,i)=>dateKey(y,m,i+1))] as (string|null)[]};
function Home(){const{state,ready,update}=useKompSaldo();const[startInput,setStartInput]=useState("");const[pickedShift,setPickedShift]=useState<ShiftId>("dag");const now=new Date();const[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const[selected,setSelected]=useState<string[]>([]);const[menu,setMenu]=useState(false);const[early,setEarly]=useState(false);const[leave,setLeave]=useState("");const dragging=useRef(false);const moved=useRef(false);const days=useMemo(()=>monthDays(month),[month]);const[compact,setCompact]=useState(()=>localStorage.getItem("kompsaldo-calendar-view")==="week");const[historyOpen,setHistoryOpen]=useState(false);
 const selectedAnchor=selected[0]??todayKey();const weekDays=useMemo(()=>{const base=new Date(`${selectedAnchor}T12:00:00`);const monday=new Date(base);monday.setDate(base.getDate()-((base.getDay()+6)%7));return Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return dateKey(d.getFullYear(),d.getMonth(),d.getDate())})},[selectedAnchor]);
 const toggleCompact=()=>setCompact(v=>{const n=!v;localStorage.setItem("kompsaldo-calendar-view",n?"week":"month");return n});
 const moveCalendar=(dir:number)=>{if(compact){const d=new Date(`${selectedAnchor}T12:00:00`);d.setDate(d.getDate()+dir*7);const k=dateKey(d.getFullYear(),d.getMonth(),d.getDate());setSelected([k]);setMonth(new Date(d.getFullYear(),d.getMonth(),1))}else setMonth(new Date(month.getFullYear(),month.getMonth()+dir,1))};
 const saveStart=()=>{const v=parseHours(startInput);if(v===null)return;const sec=Math.round(v*3600);update(s=>({...s,initialized:true,shift:pickedShift,balanceSec:sec,lastAccrual:todayKey(),history:[{id:`${Date.now()}`,date:todayKey(),deltaSec:0,type:"start",label:`Startsaldo – ${SHIFT_NAME[pickedShift]}`,balanceAfterSec:sec,manual:false},...s.history]}));setStartInput("")};
 const addSelected=(d:string)=>setSelected(v=>v.includes(d)?v:[...v,d]);const startDrag=(d:string)=>{dragging.current=true;moved.current=false;setSelected([d])};const enterDrag=(d:string)=>{if(dragging.current){moved.current=true;addSelected(d)}};const endDrag=()=>{dragging.current=false};
 const applyStatus=(type:"LEDIG"|"PAID_LEAVE"|"VACATION_DAY")=>{update(s=>selected.reduce((acc,date)=>{const sh=shiftEndForDate(getShift(acc.shift),date),t=new Date().toISOString();const deductionSec=type==="LEDIG"?fullDayDeduction(date,acc.shift):0;return upsertCalendar(acc,{id:makeId(),date,type,shift:acc.shift,shiftStart:sh.start,shiftEnd:sh.end,deductionSec,createdAt:t,updatedAt:t})},s));setSelected([]);setMenu(false)};
 const saveEarly=()=>{if(selected.length!==1||!isValidSwedishTime(leave))return;const date=selected[0]!,sh=shiftEndForDate(getShift(state.shift),date),sec=deductionSeconds(date,state.shift,leave);if(sec==null)return;const t=new Date().toISOString();update(s=>upsertCalendar(s,{id:makeId(),date,type:"LEAVE_EARLY",shift:s.shift,shiftStart:sh.start,shiftEnd:sh.end,leaveTime:leave,deductionSec:sec,createdAt:t,updatedAt:t}));setSelected([]);setMenu(false);setEarly(false);setLeave("")};
 const removeSelected=()=>{update(s=>selected.reduce((acc,date)=>{const e=acc.calendar.find(x=>x.date===date);return e?removeCalendar(acc,e.id):acc},s));setSelected([]);setMenu(false)};
 const statusClass=(date:string)=>{const e=state.calendar.find(x=>x.date===date);const vacation=isCompanyVacation(state,date)&&isWorkday(date,state.shift);if(e?.type==="LEDIG")return "day-ledig";if(e?.type==="LEAVE_EARLY")return "day-early";if(e?.type==="VACATION_DAY")return "day-vacation";if(e?.type==="PAID_LEAVE")return "day-paid";if(vacation)return "day-company-vacation";return "day-normal"};
 const CalendarGrid=({big=false,week=false}:{big?:boolean;week?:boolean})=>{const visible=week?weekDays:days;const padded=week?visible:[...visible,...Array((7-visible.length%7)%7).fill(null)];const rows=Array.from({length:Math.ceil(padded.length/7)},(_,i)=>padded.slice(i*7,i*7+7));const renderDay=(date:string|null,i:number)=>{if(!date)return <span key={`empty-${i}`}/>;const picked=selected.includes(date),today=date===todayKey();return <button key={date} data-date={date} onPointerDown={ev=>{ev.currentTarget.setPointerCapture(ev.pointerId);startDrag(date)}} onPointerMove={ev=>{if(!dragging.current)return;const el=document.elementFromPoint(ev.clientX,ev.clientY)?.closest("[data-date]") as HTMLElement|null;if(el?.dataset.date)enterDrag(el.dataset.date)}} onClick={()=>{if(moved.current){moved.current=false;return}setSelected([date])}} className={`calendar-day ${statusClass(date)} ${picked?"day-picked":""} ${today?"day-today":""}`}>{Number(date.slice(-2))}</button>};return <><div className={`calendar-weekdays ${week?"":"with-week-number"}`}>{!week&&<span className="week-number-head">V</span>}{"MÅN TIS ONS TOR FRE LÖR SÖN".split(" ").map(x=><span key={x}>{x}</span>)}</div>{week?<div className={`calendar-grid ${big?"calendar-grid-big":""}`}>{visible.map(renderDay)}</div>:<div className="calendar-month-rows">{rows.map((row,ri)=>{const first=row.find(Boolean) as string|undefined;return <div className="calendar-week-row" key={ri}><span className="week-number">{first?isoWeek(first):""}</span><div className={`calendar-grid calendar-grid-row ${big?"calendar-grid-big":""}`}>{row.map((d,i)=>renderDay(d,ri*7+i))}</div></div>})}</div>}</>};;
 const Legend=()=> <div className="legend"><span><i className="legend-dot bg-green-500"/>Ledig</span><span><i className="legend-dot bg-purple-500"/>Gå hem tidigare</span><span><i className="legend-dot bg-amber-400"/>Ledig semesterdag</span><span><i className="legend-dot bg-red-500"/>Betald ledig (Röd/klämdagar)</span><span><i className="legend-dot bg-slate-300"/>Planerad semestervecka</span></div>;
 if(!ready)return <main className="min-h-screen app-shell"/>;if(!state.initialized)return <main className="min-h-screen app-shell text-white"><div className="mx-auto max-w-md px-5 pt-12"><h1 className="text-3xl font-bold">KompSaldo</h1><section className="glass-card mt-6 p-5"><p className="font-semibold">Välj ditt skift</p><div className="mt-3 grid grid-cols-3 gap-2">{SHIFTS.map(s=><button key={s.id} onClick={()=>setPickedShift(s.id)} className={`h-14 rounded-2xl border font-semibold ${s.id===pickedShift?"border-blue-400 bg-blue-500":"border-white/15 bg-white/5"}`}>{s.name}</button>)}</div><p className="mt-3 text-sm text-white/60">Intjäning: {formatExactMin(ACCRUAL_MIN[pickedShift])} per arbetsdag</p></section><section className="glass-card mt-5 p-5"><label className="font-semibold">Fyll i ditt saldo:</label><div className="mt-3 flex gap-3"><input inputMode="decimal" value={startInput} onChange={e=>setStartInput(e.target.value)} className="h-14 w-32 rounded-2xl border border-white/15 bg-white/10 px-4 text-2xl"/><button onClick={saveStart} className="rounded-2xl bg-blue-500 px-6 font-semibold">Spara</button></div></section></div></main>;
 return <main className="min-h-screen app-shell pb-10 text-white" onPointerUp={endDrag}><div className="mx-auto max-w-md px-4 pt-8"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-2xl font-bold capitalize">{month.toLocaleDateString("sv-SE",{month:"long",year:"numeric"})}</p><p className="mt-1 max-w-xs text-sm text-white/60">En enkel överblick över din komp, ledighet och semester.</p></div><Link to="/installningar" className="top-settings-btn" aria-label="Inställningar" title="Inställningar"><Settings/></Link></div><section className="glass-card p-5"><p className="text-sm text-white/60">Kompsaldo</p><p className="mt-1 text-4xl font-bold">{formatHmSec(state.balanceSec)}</p><p className="mt-2 text-xs text-white/55">{SHIFT_NAME[state.shift]} · {formatExactMin(ACCRUAL_MIN[state.shift])} per arbetsdag</p></section>
 <section className="glass-card mt-4 p-4"><div className="flex items-center justify-between gap-2"><button onClick={()=>moveCalendar(-1)} className="icon-btn"><ChevronLeft/></button><p className="min-w-0 flex-1 text-center font-semibold capitalize">{compact?`Vecka ${(()=>{const d=new Date(`${selectedAnchor}T12:00:00`);const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const day=t.getUTCDay()||7;t.setUTCDate(t.getUTCDate()+4-day);const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return Math.ceil((((t.getTime()-y.getTime())/86400000)+1)/7)})()}, ${new Date(`${selectedAnchor}T12:00:00`).getFullYear()}`:month.toLocaleDateString("sv-SE",{month:"long",year:"numeric"})}</p><div className="flex gap-2"><button onClick={toggleCompact} className="icon-btn" aria-label={compact?"Visa månad":"Visa en vecka"}>{compact?<ChevronDown/>:<ChevronUp/>}</button><button onClick={()=>moveCalendar(1)} className="icon-btn"><ChevronRight/></button></div></div><CalendarGrid week={compact}/><Legend/></section>
 {selected.length>0&&<button onClick={()=>setMenu(true)} className="mt-4 h-14 w-full rounded-2xl bg-blue-500 font-semibold">Hantera {selected.length===1?"vald dag":`${selected.length} valda dagar`}</button>}
 <div className="mt-4 grid gap-3"><button onClick={()=>setHistoryOpen(true)} className="nav-card w-full text-left"><History/><span>Historik</span><ChevronRight className="ml-auto"/></button></div></div>

 {historyOpen&&<div className="fixed inset-0 z-50 calendar-overlay" onClick={e=>{if(e.target===e.currentTarget)setHistoryOpen(false)}}><section className="calendar-modal history-modal p-5 text-white"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Historik</h2><p className="mt-1 text-sm text-white/55">Senaste ändringarna av ditt kompsaldo</p></div><button className="icon-btn" onClick={()=>setHistoryOpen(false)} aria-label="Stäng historik"><X/></button></div><div className="history-list mt-5">{(()=>{const autoByDate=new Map(state.history.filter(h=>h.type==="auto").map(h=>[h.date,h]));const calendarRows=state.calendar.map(e=>{const auto=autoByDate.get(e.date);const earned=auto?.deltaSec??0;const effect=e.balanceEffectSec??0;const label=e.type==="LEDIG"?"Ledig":e.type==="LEAVE_EARLY"?"Gå hem tidigare":e.type==="VACATION_DAY"?"Ledig semesterdag":e.type==="PAID_LEAVE"?"Betald ledig (Röd/klämdagar)":"Registrering";return{id:`cal-${e.id}`,date:e.date,label,earned,deduction:e.deductionSec,delta:earned+effect,kind:"calendar"}});const calendarDates=new Set(state.calendar.map(e=>e.date));const otherRows=state.history.filter(h=>h.type!=="auto"||!calendarDates.has(h.date)).map(h=>({id:`hist-${h.id}`,date:h.date,label:h.label,earned:h.type==="auto"?h.deltaSec:0,deduction:0,delta:h.deltaSec,kind:"history"}));const rows=[...calendarRows,...otherRows].sort((a,b)=>b.date.localeCompare(a.date));if(!rows.length)return <div className="history-empty">Ingen historik ännu.</div>;return rows.map(r=><article className="history-item" key={r.id}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{r.label}</p><p className="mt-1 text-xs text-white/50">{new Date(`${r.date}T12:00:00`).toLocaleDateString("sv-SE",{day:"numeric",month:"long",year:"numeric"})} · Vecka {isoWeek(r.date)}</p></div><strong className={r.delta<0?"history-negative":r.delta>0?"history-positive":"history-neutral"}>{r.delta>0?"+":""}{formatHmSec(r.delta)}</strong></div>{r.kind==="calendar"&&<div className="history-details"><span>Intjänad komp <b>{r.earned>0?"+":""}{formatHmSec(r.earned)}</b></span>{r.deduction>0&&<span>Avdrag <b>−{formatHmSec(r.deduction)}</b></span>}<span>Netto <b>{r.delta>0?"+":""}{formatHmSec(r.delta)}</b></span></div>}</article>)})()}</div></section></div>}

 {menu&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 p-4 backdrop-blur-sm"><div className="glass-modal w-full max-w-md rounded-3xl p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">{selected.length} {selected.length===1?"vald dag":"valda dagar"}</h2><button onClick={()=>{setMenu(false);setEarly(false)}}><X/></button></div>{!early?<div className="mt-5 space-y-2"><button onClick={()=>applyStatus("LEDIG")} className="action-btn bg-green-500">Ledig</button><button disabled={selected.length!==1} onClick={()=>setEarly(true)} className="action-btn bg-purple-500 disabled:opacity-40"><Clock3 size={19}/> Gå hem tidigare</button><button onClick={()=>applyStatus("VACATION_DAY")} className="action-btn bg-amber-500">Ledig semesterdag</button><button onClick={()=>applyStatus("PAID_LEAVE")} className="action-btn bg-red-500">Betald ledig (Röd/klämdagar)</button><button onClick={removeSelected} className="action-btn border border-red-400/70 bg-transparent text-red-300"><Trash2 size={18}/> Ta bort registrering</button></div>:<div className="mt-5"><label className="text-sm font-semibold">Tid du går hem</label><input type="text" inputMode="numeric" autoComplete="off" placeholder="14:30" maxLength={5} aria-label="Tid du går hem i 24-timmarsformat" value={leave} onChange={e=>setLeave(formatSwedishTimeInput(e.target.value))} className="mt-2 h-16 w-full rounded-2xl border border-white/15 bg-white/10 px-4 text-2xl font-semibold tracking-wider"/><p className="mt-2 text-xs text-white/55">Svensk tid · 24-timmarsformat (HH:MM), t.ex. 14:30</p>{selected[0]&&state.shift==="natt"&&new Date(`${selected[0]}T12:00:00`).getDay()===0&&!SUNDAY_NIGHT_UNPAID_BREAK&&<p className="mt-3 text-sm text-red-300">Söndagsnattens obetalda rast saknas, därför gör appen ingen gissning.</p>}<button onClick={saveEarly} className="mt-4 h-14 w-full rounded-2xl bg-purple-500 font-semibold">Bekräfta</button></div>}</div></div>}</main>}
