/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaHemRouteImport } from './routes/ga-hem'
import { Route as InstallningarRouteImport } from './routes/installningar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaHemRoute = GaHemRouteImport.update({
  id: '/ga-hem',
  path: '/ga-hem',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallningarRoute = InstallningarRouteImport.update({
  id: '/installningar',
  path: '/installningar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ga-hem': typeof GaHemRoute
  '/installningar': typeof InstallningarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ga-hem': typeof GaHemRoute
  '/installningar': typeof InstallningarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ga-hem': typeof GaHemRoute
  '/installningar': typeof InstallningarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ga-hem' | '/installningar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ga-hem' | '/installningar'
  id: '__root__' | '/' | '/ga-hem' | '/installningar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaHemRoute: typeof GaHemRoute
  InstallningarRoute: typeof InstallningarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga-hem': {
      id: '/ga-hem'
      path: '/ga-hem'
      fullPath: '/ga-hem'
      preLoaderRoute: typeof GaHemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installningar': {
      id: '/installningar'
      path: '/installningar'
      fullPath: '/installningar'
      preLoaderRoute: typeof InstallningarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaHemRoute: GaHemRoute,
  InstallningarRoute: InstallningarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
